DELETE http://localhost:3003/api/blogs/6226b46b377367e6a3b84f34
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1yYnVuYnVuIiwiaWQiOiI2MjI2OTQyNTM0NmRkN2ZmNjllZTlmNDAiLCJpYXQiOjE2NDY3MDMyMzl9._PbHo2EvHc_I4mAW2Vtu-rFTEBzktD3voTts-_Xaj9I